{
 "title": "Prisma Metrics Example Dashboard",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "95% Total Prisma Query Elapsed Time vs Datasource Query Elapsed Time",
   "type": "timeseries",
   "description": "More about quantile estimations: https://prometheus.io/docs/practices/histograms/#quantiles",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(prisma_client_queries_duration_histogram_ms_bucket[$__rate_interval])))",
     "legendFormat": "Prisma Query Elapsed Time"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(prisma_datasource_queries_duration_histogram_ms_bucket[$__rate_interval])))",
     "legendFormat": "Datasource Query Elapsed Time"
    }
   ]
  },
  {
   "title": "Active vs Idle connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "prisma_pool_connections_open", "legendFormat": "Active Connections" },
    { "expr": "prisma_pool_connections_idle", "legendFormat": "Idle Connections" },
    { "expr": "pool_wait_count", "legendFormat": "Waiting For Connection" }
   ]
  },
  {
   "title": "Prisma Query Count vs Datasource Query (Per Unit Time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(prisma_client_queries_total[$__rate_interval])",
     "legendFormat": "Prisma Query Count"
    },
    {
     "expr": "rate(prisma_datasource_queries_total[$__rate_interval])",
     "legendFormat": "Datasource Query Count"
    }
   ]
  },
  {
   "title": "Active Queries vs Waiting Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "prisma_client_queries_active", "legendFormat": "Active Transactions" },
    { "expr": "prisma_client_queries_wait", "legendFormat": "Queries Waiting for Connection" }
   ]
  }
 ]
}